# MercadoPago DataSource (escritura)
app.datasource.mercadopago.enabled=true
app.datasource.mercadopago.jdbc-url=jdbc:sqlserver://192.168.1.123:1433;databaseName=MercadoPagoSync;encrypt=true;trustServerCertificate=true
app.datasource.mercadopago.username=###
app.datasource.mercadopago.password=###
app.datasource.mercadopago.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# MercadoPago API
mercadopago.access-token=${MERCADOPAGO_API_KEY}
mercadopago.sync.days-back=140
mercadopago.sync.page-size=100
# Scheduling (cada hora)
app.scheduling.enabled=true
spring.application.name=mercadopago-sync
server.port=9081
# Verina DataSource (espejo de MP)
app.datasource.verina.enabled=false
app.datasource.verina.jdbc-url=jdbc:sqlserver://DESARROLLO\\SQLEXPRESS;databaseName=BatteryPlus;encrypt=true;trustServerCertificate=true
app.datasource.verina.username=${DATASOURCE_DB_USER}
app.datasource.verina.password=${DATASOURCE_DB_PASS}
app.datasource.verina.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# BatteryPlus DataSource (lectura)
app.datasource.batteryplus.enabled=true
app.datasource.batteryplus.jdbc-url=jdbc:sqlserver://purabateria-server.database.windows.net:1433;databaseName=BatteryPlus;encrypt=true;trustServerCertificate=true;loginTimeout=30
app.datasource.batteryplus.username=${VERINA_DB_USER}
app.datasource.batteryplus.password=${VERINA_DB_PASS}
app.datasource.batteryplus.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver